# Generated by Django 5.1.6 on 2025-02-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_background', models.ImageField(upload_to='backgrounds/', verbose_name='Restoran Arkaplan Görseli')),
                ('bar_background', models.ImageField(upload_to='backgrounds/', verbose_name='Bar Arkaplan Görseli')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Anasayfa Ayarları',
                'verbose_name_plural': 'Anasayfa Ayarları',
            },
        ),
    ]
