# Generated by Django 5.1.6 on 2025-02-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodanddrink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='bar_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Bar Arkaplan Görseli'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='restaurant_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Restoran Arkaplan Görseli'),
        ),
    ]
