# Generated by Django 5.0.1 on 2025-02-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodanddrink', '0003_review_reviewresponse_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
