# Generated by Django 5.0.1 on 2025-02-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodanddrink', '0004_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewresponse',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Düzenlendi mi?'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Düzenlenme Tarihi'),
        ),
    ]
