# Generated by Django 5.0.1 on 2025-02-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodanddrink', '0010_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewresponse',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewresponse',
            name='responded_by',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewResponse',
        ),
    ]
