# Generated by Django 5.0.1 on 2025-02-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodanddrink', '0011_remove_review_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ödeme ID'),
        ),
    ]
