# Generated by Django 5.1.6 on 2025-02-12 20:48

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='restaurant/categories/', verbose_name='Kategori Görseli')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('time', models.TimeField(verbose_name='Saat')),
                ('guests', models.PositiveIntegerField(verbose_name='Kişi Sayısı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rezervasyon',
                'verbose_name_plural': 'Rezervasyonlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Restoran Adı')),
                ('logo', models.ImageField(upload_to='restaurant/logos/', verbose_name='Logo')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('opening_hours', models.CharField(max_length=100, verbose_name='Çalışma Saatleri')),
            ],
            options={
                'verbose_name': 'Restoran Bilgisi',
                'verbose_name_plural': 'Restoran Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('image', models.ImageField(upload_to='restaurant/menu_items/', verbose_name='Ürün Görseli')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mevcut mu?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Menü Ürünü',
                'verbose_name_plural': 'Menü Ürünleri',
                'ordering': ['category', 'name'],
            },
        ),
    ]
