# Generated by Django 5.1.6 on 2025-02-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurantinfo_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/categories/', verbose_name='Kategori Görseli'),
        ),
    ]
