# Generated by Django 5.0.1 on 2025-02-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_menuitem_allergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='friday_hours',
            field=models.CharField(default='09:00 - 22:00', max_length=50, verbose_name='Cuma'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='monday_hours',
            field=models.CharField(default='09:00 - 22:00', max_length=50, verbose_name='Pazartesi'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='saturday_hours',
            field=models.CharField(default='10:00 - 23:00', max_length=50, verbose_name='Cumartesi'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='sunday_hours',
            field=models.CharField(default='10:00 - 23:00', max_length=50, verbose_name='Pazar'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='thursday_hours',
            field=models.CharField(default='09:00 - 22:00', max_length=50, verbose_name='Perşembe'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='tuesday_hours',
            field=models.CharField(default='09:00 - 22:00', max_length=50, verbose_name='Salı'),
        ),
        migrations.AddField(
            model_name='restaurantinfo',
            name='wednesday_hours',
            field=models.CharField(default='09:00 - 22:00', max_length=50, verbose_name='Çarşamba'),
        ),
    ]
