# Generated by Django 5.1.6 on 2025-02-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barinfo',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='bar/hero/', verbose_name='Hero Arkaplan Görseli'),
        ),
        migrations.AddField(
            model_name='barinfo',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Ana sayfadaki açıklama metni', verbose_name='Hero Alt Başlık'),
        ),
        migrations.AddField(
            model_name='barinfo',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Ana sayfadaki büyük başlık', max_length=200, verbose_name='Hero Başlık'),
        ),
    ]
