# Generated by Django 5.1.6 on 2025-02-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_barinfo_hero_image_barinfo_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bar/categories/', verbose_name='Kategori Görseli'),
        ),
    ]
