# Generated by Django 5.1.6 on 2025-02-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_alter_drinkcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bar/gallery/', verbose_name='Resim')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Başlık')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Bar Galeri',
                'verbose_name_plural': 'Bar Galeri',
                'ordering': ['-created_at'],
            },
        ),
    ]
