# Generated by Django 5.1.6 on 2025-02-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_bargallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='alcohol_content',
            field=models.CharField(choices=[('none', 'Alkolsüz'), ('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='none', max_length=10, verbose_name='Alkol Oranı'),
        ),
        migrations.AddField(
            model_name='drink',
            name='allergens',
            field=models.TextField(blank=True, verbose_name='Alerjenler'),
        ),
        migrations.AddField(
            model_name='drink',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kalori'),
        ),
        migrations.AddField(
            model_name='drink',
            name='dietary_restrictions',
            field=models.JSONField(blank=True, default=list, verbose_name='Diyet Gereksinimleri'),
        ),
        migrations.AddField(
            model_name='drink',
            name='preparation_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hazırlama Süresi (dakika)'),
        ),
        migrations.AddField(
            model_name='drink',
            name='price_range',
            field=models.CharField(choices=[('low', 'Ekonomik'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=10, verbose_name='Fiyat Aralığı'),
        ),
    ]
