# Generated by Django 5.1.6 on 2025-02-13 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_drink_alcohol_content_drink_allergens_drink_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İçecek Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='drink_items/', verbose_name='Görsel')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('price_range', models.CharField(choices=[('low', 'Ekonomik'), ('medium', 'Orta'), ('high', 'Yüksek')], default='medium', max_length=10, verbose_name='Fiyat Aralığı')),
                ('alcohol_content', models.CharField(choices=[('none', 'Alkolsüz'), ('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek')], default='none', max_length=10, verbose_name='Alkol Oranı')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Ortalama Puan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.drinkcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'İçecek',
                'verbose_name_plural': 'İçecekler',
            },
        ),
    ]
