# Generated by Django 5.0.1 on 2025-02-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0006_drinkitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Ortalama Puan'),
        ),
    ]
