# Generated by Django 5.0.1 on 2025-02-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0007_drink_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='preparation_time',
        ),
        migrations.AlterField(
            model_name='drink',
            name='alcohol_content',
            field=models.CharField(choices=[('none', 'Alkolsüz'), ('low', 'Düşük Alkollü (%1-%5)'), ('medium', 'Orta Alkollü (%6-%12)'), ('high', 'Yüksek Alkollü (%12+)')], default='none', max_length=10, verbose_name='Alkol Oranı'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='İçindekiler'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
