# Generated by Django 5.0.1 on 2025-02-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_remove_drink_allergens_remove_drink_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barinfo',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='barinfo',
            name='friday_hours',
            field=models.CharField(default='16:00 - 04:00', max_length=50, verbose_name='Cuma'),
        ),
        migrations.AddField(
            model_name='barinfo',
            name='monday_hours',
            field=models.CharField(default='16:00 - 02:00', max_length=50, verbose_name='Pazartesi'),
        ),
        migrations.AddField(
            model_name='barinfo',
            name='saturday_hours',
            field=models.CharField(default='16:00 - 04:00', max_length=50, verbose_name='Cumartesi'),
        ),
        migrations.AddField(
            model_name='barinfo',
            name='sunday_hours',
            field=models.CharField(default='16:00 - 02:00', max_length=50, verbose_name='Pazar'),
        ),
        migrations.AddField(
            model_name='barinfo',
            name='thursday_hours',
            field=models.CharField(default='16:00 - 02:00', max_length=50, verbose_name='Perşembe'),
        ),
        migrations.AddField(
            model_name='barinfo',
            name='tuesday_hours',
            field=models.CharField(default='16:00 - 02:00', max_length=50, verbose_name='Salı'),
        ),
        migrations.AddField(
            model_name='barinfo',
            name='wednesday_hours',
            field=models.CharField(default='16:00 - 02:00', max_length=50, verbose_name='Çarşamba'),
        ),
    ]
